### ISSUE TITLE
edb.components.set_solder_ball shape "None" not available through EDB API

### ISSUE THREAD

**Issue by askoeho** [ansys/pyedb#238]
### Description of the feature

It would be helpful if all available options are presented to EDB API. "None" is not available for solder ball shapes but this can be done manually in HFSS 3D Layout.

### Steps for implementing the feature

Add "None" to edb.components.set_solder_ball shape types.

### Useful links and references

This can be selected manually in HFSS 3D Layout

![image](https://github.com/ansys/pyedb/assets/5597705/0de0fec9-b6e3-4eda-b30e-3ab228ceef09)

**Comment by svandenb-dev** [comment]
@askoeho setting to None would remove the solder balls is that what you want ?

**Comment by askoeho** [comment]
@svandenb-dev yes exactly.

**Comment by svandenb-dev** [comment]
@askoeho I created a pull request with adding property getter and setters from component instances so that you can simply get and set:
solder balls height
solder balls shape
solder balls diameter.

Please give it a try. My test is passing and I would like to know if it works on your project.
If you work on dev branch from github you can grab the corresponding branch. If you work from PyEDB package please wait release 0.5.3.
BR
