### ISSUE TITLE
Materials are not read correctly.

### ISSUE THREAD

**Issue by gkorompi** [ansys/pyedb#360]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

NA

### Steps To Reproduce

import pyedb
import os
from pyedb.dotnet.edb import Edb
edbapp = Edb()
edbapp.stackup.add_layer("bot_gnd",thickness="0.65mil")

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

NA

**Comment by SMoraisAnsys** [comment]
For clarification, materials are correctly read. It is just that the refactoring of the `Material` and `Materials` classes removed the automatic creation of "air", "copper", "fr4_epoxy", "solder_mask". This is because they were conflicting with the material from the syslib AMAT file.

PR #361 should correct that by creating, on the fly, requested materials if they do not exist (from syslib values).
If you have other cases were something seems to be going wrong, please extend this issue or open a new one.
