### ISSUE TITLE
edb.hfss.create_circuit_port_on_pin creates only one circuit port if used multiple times

### ISSUE THREAD

**Issue by askoeho** [ansys/pyedb#479]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

I'm trying to add two circuits ports using edb.hfss.create_circuit_port_on_pin. Only the first one is created as a circuit port, the second one is a gap port. Used Ansys EM Suite version is 2024R1.1.

![image](https://github.com/ansys/pyedb/assets/5597705/09781f74-9487-4a79-8995-8c3148f387ac)

### Steps To Reproduce

```
import pyedb
import pyaedt
from pyedb.generic.general_methods import generate_unique_folder_name
from pyedb.misc.downloads import download_file

import datetime

hfss_version = "2024.1"

temp_folder = generate_unique_folder_name()
targetfile = download_file("edb/ANSYS-HSD_V1.aedb", destination=temp_folder)

my_edb = pyedb.Edb(edbpath=targetfile, edbversion=hfss_version)

now = datetime.datetime.now()
t = now.strftime("%Y%m%d%H%M%S")

output_file = r"C:\ansys_example\circuit_ports_example\output_edb\circuit_port_example_output_file_" + t + ".aedb"

port_pos_pin = my_edb.components.get_pin_from_component(component="C176")[1] #index=real pin number - 1
port_neg_pin = my_edb.components.get_pin_from_component(component="C174")[0]
my_edb.hfss.create_circuit_port_on_pin(pos_pin = port_pos_pin, neg_pin = port_neg_pin, impedance = 50)

port_pos_pin = my_edb.components.get_pin_from_component(component="C173")[1]
port_neg_pin = my_edb.components.get_pin_from_component(component="C172")[0]
my_edb.hfss.create_circuit_port_on_pin(pos_pin = port_pos_pin, neg_pin = port_neg_pin, impedance = 50)

my_edb.save_as(output_file)
my_edb.close()

h3d = pyaedt.Hfss3dLayout(projectname=output_file, specified_version=hfss_version)
h3d.save_project()
h3d.release_desktop(close_projects=False, close_desktop=False)
```

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

```
annotated-types==0.6.0
ansys-pythonnet==3.1.0rc3
attrs==23.2.0
cffi==1.16.0
clr-loader==0.2.6
defusedxml==0.7.1
fonttools==4.51.0
fpdf2==2.7.8
jsonschema==4.22.0
jsonschema-specifications==2023.12.1
numpy==1.26.4
pillow==10.3.0
plumbum==1.8.3
psutil==5.9.8
pyaedt==0.9.1
pycparser==2.22
pydantic==2.7.1
pydantic_core==2.18.2
pyedb==0.10.0
pytomlpp==1.0.13
pywin32==306
referencing==0.35.1
rpds-py==0.18.1
rpyc==6.0.0
Rtree==1.2.0
toml==0.10.2
typing_extensions==4.11.0
```

**Comment by gkorompi** [comment]
hello @askoeho, the port that you are using for defining the ports will be refactored, so please use the following commands:

pos_pin = edbapp.padstacks.get_pinlist_from_component_and_net("C173")[1]
neg_pin = edbapp.padstacks.get_pinlist_from_component_and_net("C172")[0]
edbapp.create_port(pos_pin.get_terminal(create_new_terminal=True), neg_pin.get_terminal(create_new_terminal=True), is_circuit_port = True)

pos_pin = edbapp.padstacks.get_pinlist_from_component_and_net("C176")[1]
neg_pin = edbapp.padstacks.get_pinlist_from_component_and_net("C174")[0]
edbapp.create_port(pos_pin.get_terminal(create_new_terminal=True), neg_pin.get_terminal(create_new_terminal=True), is_circuit_port = True)

here, we create a new terminal on each pin, so that the ports have where to be created on. What i think happens in the definition you use is that there is not a terminal, or it used by the other port. 

I hope this helps! 
Georgios

**Comment by askoeho** [comment]
@gkorompi Thank you for the example! This example works as expected.

**Comment by askoeho** [comment]
@gkorompi maybe one question regarding this new method. This creates a new Terminal which gives totally random port naming and meshing warnings. Any way to avoid this?

**Comment by gkorompi** [comment]
@askoeho Ok i just added, you can check this on the corresponding PR. It will be included in the following pyedb release. Thanks for your contribution
