### ISSUE TITLE
The default permeability value of new material cannot be 0

### ISSUE THREAD

**Issue by hui-zhou-a** [ansys/pyedb#827]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

The default permeability of new material is should 1.

### Steps To Reproduce

add_material

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

all

**Comment by SMoraisAnsys** [comment]
@hui-zhou-a I can work on that. Can you let me know what is the scope of this ?
Currently, it seem that we leverage the EDB API to retrieve permeability and do not force 0 as default value.
In fact, if you look at `add_material` in control_file, the default value is `1.0` for permeability.

So, in which case would you want to apply the improvement you mention ?

**Comment by hui-zhou-a** [comment]
@SMoraisAnsys that's right pyedb doesn't force permeability. However, the default value from EDB API is 0 :d. We need to force permeability=1 if not defined.

**Comment by svandenb-dev** [comment]
fully agree

**Comment by hui-zhou-a** [comment]
Sorry. I mean make permeability default value=1. The user for sure can change it.

**Comment by SMoraisAnsys** [comment]
@hui-zhou-a So that means that we won't use the EDB API to retrieve the permeability ?
Currently when a user tries to access to permeability, we are using the EDB API to retrieve that information (and the return value might not be the one you wanted). It is still unclear to me how to distinguish those cases ? Let's say you want to use `vaccum`, defaulting the 1 will be a problem... Same case for any material that the user creates with permeability equal to 0.
